# Generated by Django 3.2.5 on 2021-08-22 14:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flow_DB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 14, 44, 40, 613952, tzinfo=utc), verbose_name='date published'),
        ),
    ]
