# Generated by Django 3.2.5 on 2021-08-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_DB', '0003_alter_flow_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
