# Generated by Django 3.2.5 on 2021-08-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_wylewanie', models.IntegerField(default=0)),
                ('time_I_pole', models.IntegerField(default=0)),
                ('time_II_pole', models.IntegerField(default=0)),
                ('time_III_pole', models.IntegerField(default=0)),
            ],
        ),
    ]
